export const pharmacyRoutes = {
  overview: "/pharmacy/overview",
  prescriptions: "/pharmacy/prescriptions",
  billing: "/pharmacy/billing",
  inventory: "/pharmacy/inventory",
  catalog: "/pharmacy/catalog",
  medicines: "/pharmacy/medicines",
  addMedicine: "/pharmacy/medicines/add",
  orders: "/pharmacy/orders",
  customers: "/pharmacy/customers",
  reviews: "/pharmacy/reviews",
  deliveries: "/pharmacy/deliveries",
  multistore: "/pharmacy/multistore",
  earnings: "/pharmacy/earnings",
  pricing: "/pharmacy/pricing",
  analytics: "/pharmacy/analytics",
  store: "/pharmacy/store",
  settings: "/pharmacy/settings",
} as const;
